In [6]:
import pandas as pd

In [7]:
p = pd.read_csv("processed_data/software_eng.csv")

In [8]:
p

,Surname,First_Name,Cognome e Nome,Genere,S.S.D.,ateneo,ID,fascia_id,Scopus_id,Total_Papers,...,ASE_2015,ASE_2014,MSR_2014,RE_2020,ECSA_2017,ICSA_2023,ICSA_2015,ICSA_2019,SEAMS_2016,SEAMS_2015
0,Russo,Barbara,RUSSO Barbara,F,INF/01,Libera Università di BOLZANO,68004,1,9-s2.0-9335579000,97.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Risi,Michele,RISI Michele,M,INF/01,SALERNO,34214,0,9-s2.0-9275600300,117.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Lluch lafuente,Alberto,LLUCH LAFUENTE Alberto,M,INF/01,Scuola IMT Alti Studi LUCCA,14859,0,9-s2.0-9245337700,108.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Lanese,Ivan,LANESE Ivan,M,INF/01,BOLOGNA,19441,0,9-s2.0-8984182000,131.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Fasano,Fausto,FASANO Fausto,M,INF/01,MOLISE,50673,1,9-s2.0-8971191700,40.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,Inverardi,Paola,INVERARDI Paola,F,INF/01,L_AQUILA,2234,2,0,0.0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0
121,Tiezzi,Francesco,TIEZZI Francesco,M,INF/01,Scuola IMT Alti Studi LUCCA,14865,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122,Falcarin,Paolo,FALCARIN Paolo,M,ING-INF/05,Ca_ Foscari VENEZIA,77774,1,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
123,Castelluccia,Daniela,CASTELLUCCIA Daniela,F,ING-INF/05,Univ. Telematica E-CAMPUS,45570,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
124,Muttillo,Vittoriano,MUTTILLO Vittoriano,M,ING-INF/05,TERAMO,264,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
p['ID'] = p.index
p = p.drop(columns=['Surname','First_Name','Cognome e Nome'])

In [10]:
p.to_csv("ita_software_eng.csv")